#!/usr/bin/env python3
"""Index and check the prior-art databank (docs/prior-art/).

An entry is keyed by domain and slug: a subject may appear in two domains.

Reads every entry's frontmatter, checks it against TEMPLATE.md's fields,
and writes two files next to the entries:

  INDEX.md    one table per domain, and counts by status and relevance
  index.json  the same records, for a script or a query with jq

Exits 1 when an entry is malformed, so it can run before a commit.

  dev/prior-art-index.py            # check and write
  dev/prior-art-index.py --check    # check only
"""

import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "docs" / "prior-art"
FIELDS = ["name", "slug", "domain", "kind", "platform", "vendor", "years",
          "status", "tags", "relevance"]
SECTIONS = ["## What it is", "## What was new", "## What went wrong / limits",
            "## Lessons for swaypplet", "## Sources"]
DOMAINS = {
    "shells": "Desktop shells and OS desktop UI",
    "mobile": "Mobile, wearable, TV and spatial UI",
    "launchers": "Launchers, command palettes and search",
    "wayland": "Wayland, tiling and custom shells",
    "theming": "Theming, colour, materials and settings",
    "notifications-wm": "Notifications, focus, widgets, window management, failures",
    "motion": "Motion, rendering and performance",
}


def frontmatter(text):
    """The `key: value` lines between the first two `---` lines."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    out = {}
    for line in lines[1:]:
        if line.strip() == "---":
            return out
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        value = value.split(" #", 1)[0].strip()
        if value.startswith("[") and value.endswith("]"):
            value = [v.strip() for v in value[1:-1].split(",") if v.strip()]
        out[key.strip()] = value
    return None


def main():
    check_only = "--check" in sys.argv
    records, errors, slugs = [], [], Counter()
    for path in sorted(ROOT.glob("*/*.md")):
        if path.name == "README.md":
            continue
        text = path.read_text(encoding="utf-8")
        fm = frontmatter(text)
        rel = path.relative_to(ROOT)
        if fm is None:
            errors.append(f"{rel}: no frontmatter")
            continue
        missing = [f for f in FIELDS if f not in fm]
        if missing:
            errors.append(f"{rel}: missing {', '.join(missing)}")
        if fm.get("slug") != path.stem:
            errors.append(f"{rel}: slug {fm.get('slug')!r} is not the file name")
        if fm.get("domain") != path.parent.name:
            errors.append(f"{rel}: domain {fm.get('domain')!r} is not its folder")
        for section in SECTIONS:
            if section not in text:
                errors.append(f"{rel}: no '{section}'")
        slugs[(path.parent.name, path.stem)] += 1
        fm["path"] = str(rel)
        records.append(fm)
    # A subject may be entered from two domains, each with its own lens;
    # within one domain a slug is unique.
    for (domain, slug), n in slugs.items():
        if n > 1:
            errors.append(f"slug {slug!r} used {n} times in {domain}")
    by_slug = {}
    for r in records:
        by_slug.setdefault(r["slug"], []).append(r["path"])
    shared = {k: v for k, v in by_slug.items() if len(v) > 1}

    for e in errors:
        print(e, file=sys.stderr)
    if check_only or errors:
        print(f"{len(records)} entries, {len(errors)} problems")
        return 1 if errors else 0

    (ROOT / "index.json").write_text(
        json.dumps(records, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")

    status = Counter(r.get("status", "?") for r in records)
    relevance = Counter(r.get("relevance", "?") for r in records)
    md = ["# Prior-art index", "",
          "Generated by `dev/prior-art-index.py` from the entries' frontmatter;"
          " do not edit by hand. The synthesis is [README.md](README.md).", "",
          f"**{len(records)} entries.** Status: "
          + ", ".join(f"{k} {v}" for k, v in status.most_common())
          + ". Relevance to swaypplet: "
          + ", ".join(f"{k} {v}" for k, v in relevance.most_common()) + ".", ""]
    order = {"high": 0, "medium": 1, "low": 2}
    for domain, title in DOMAINS.items():
        rows = [r for r in records if r.get("domain") == domain]
        if not rows:
            continue
        rows.sort(key=lambda r: (order.get(r.get("relevance"), 3), r.get("name", "").lower()))
        md += [f"## {title} ({len(rows)})", "",
               f"Synthesis: [{domain}/README.md]({domain}/README.md)", "",
               "| Entry | Kind | Platform | Years | Status | Relevance |",
               "|---|---|---|---|---|---|"]
        for r in rows:
            md.append(f"| [{r.get('name')}]({r['path']}) | {r.get('kind')} | {r.get('platform')}"
                      f" | {r.get('years')} | {r.get('status')} | {r.get('relevance')} |")
        md.append("")
    if shared:
        md += ["## Seen from two domains", "",
               "The same subject, entered by two domains for different lessons.", ""]
        for slug, paths in sorted(shared.items()):
            md.append(f"- `{slug}`: " + ", ".join(f"[{p}]({p})" for p in paths))
        md.append("")
    (ROOT / "INDEX.md").write_text("\n".join(md), encoding="utf-8")
    print(f"{len(records)} entries indexed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
