//! Every layer-shell namespace swaypplet asks for, in one table.
//!
//! A namespace is not a label. The compositor keys a surface's material on
//! it (`layer_effects "<namespace>"` in the sway config, generated by the
//! nixos repo's `users/modules/theme/glass-config.nix` from its
//! `sessionSurfaces` table), the settings pane pushes live edits at it
//! (`settings::glass::System::surfaces`, read from `/etc/swaypplet/glass.json`,
//! which Nix writes from that same table), and `anim::set_layer_blur` counts
//! surfaces per namespace. A string spelled slightly differently in one
//! `LayerShellConfig` is a surface with no glass and no error anywhere, so
//! the spelling lives here and nowhere else (design lint `layer-namespace`).

/// A layer-shell namespace (see the module docs for why this is a type).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Namespace {
    /// The control centre (Helm), `app.rs`.
    Panel,
    /// One per output, `bar/`.
    Bar,
    /// The launcher, and the dmenu picker that borrows its chassis and its
    /// material.
    Launcher,
    /// The volume/brightness/lock-key card, one per output.
    Osd,
    /// One surface per popup card.
    Notification,
    /// A pinned workspace or region, `jump/pin.rs`.
    Pin,
    /// Screenshot → window: the grid of live windows.
    WindowPicker,
    /// The polkit / sudo card.
    Polkit,
    /// The report card: a description and a screenshot on their way to an
    /// issue (`quality/report.rs`).
    Report,
    /// The look-at-the-camera pill over the polkit card.
    FaceCue,
    /// The held-Super keybinding sheet, one per output.
    Keybinds,
    /// The Super+Tab stage.
    Jump,
    /// The frozen screen the region selector draws on. Deliberately without
    /// glass: it must show the screen, not frost it.
    Screenshot,
    /// The greeter's card, one per output, on the greeter's own compositor.
    Greeter,
    /// The one-pixel surface the locker maps and destroys to warm GTK up.
    LockWarm,
    /// Not a layer-shell namespace on a real session: the compositor applies
    /// this block to session-lock surfaces. `preview:lock` borrows it for a
    /// layer surface so the harness can draw the lock card's glass.
    SessionLock,
    /// A namespace no surface uses, for asking sway what `layer_effects`
    /// options it parses (`anim::motion_support`).
    MotionProbe,
    /// The black sheet over the animated wallpaper, one per output, that
    /// fades it to black on battery (`services::wallpaper_curtain`).
    /// Deliberately without glass: it is plain black, and a `layer_effects`
    /// block on it would frost the desktop it is fading out.
    WallpaperCurtain,
}

impl Namespace {
    pub const ALL: [Namespace; 18] = [
        Namespace::Panel,
        Namespace::Bar,
        Namespace::Launcher,
        Namespace::Osd,
        Namespace::Notification,
        Namespace::Pin,
        Namespace::WindowPicker,
        Namespace::Polkit,
        Namespace::Report,
        Namespace::FaceCue,
        Namespace::Keybinds,
        Namespace::Jump,
        Namespace::Screenshot,
        Namespace::Greeter,
        Namespace::LockWarm,
        Namespace::SessionLock,
        Namespace::MotionProbe,
        Namespace::WallpaperCurtain,
    ];

    /// The string the compositor sees.
    pub const fn as_str(self) -> &'static str {
        match self {
            Namespace::Panel => "swaypplet",
            Namespace::Bar => "swaypplet-bar",
            Namespace::Launcher => "swaypplet-launcher",
            Namespace::Osd => "swaypplet-osd",
            Namespace::Notification => "swaypplet-notification",
            Namespace::Pin => "swaypplet-pin",
            Namespace::WindowPicker => "swaypplet-window-picker",
            Namespace::Polkit => "swaypplet-polkit",
            Namespace::Report => "swaypplet-report",
            Namespace::FaceCue => "swaypplet-face-cue",
            Namespace::Keybinds => "swaypplet-keybinds",
            Namespace::Jump => "swaypplet-jump",
            Namespace::Screenshot => "swaypplet-screenshot",
            Namespace::Greeter => "swaypplet-greeter",
            Namespace::LockWarm => "swaypplet-lock-warm",
            Namespace::SessionLock => "session-lock",
            Namespace::MotionProbe => "swaypplet-motion-probe",
            Namespace::WallpaperCurtain => "swaypplet-curtain",
        }
    }

    /// The namespace the compositor calls `s`, if it is one of ours.
    pub fn parse(s: &str) -> Option<Namespace> {
        Namespace::ALL.into_iter().find(|n| n.as_str() == s)
    }

    /// The glass geometry class the session's sway config gives this
    /// namespace (`thin`, `panel`, `lock`), or `None` for one it leaves
    /// without material.
    ///
    /// The session's table is Nix's (`sessionSurfaces` in the nixos repo's
    /// `users/modules/theme/glass-config.nix`), and it reaches this process
    /// as `/etc/swaypplet/glass.json`'s `surfaces` map. This is the copy the
    /// code keeps of it, so a surface added here without a row there, or a
    /// row there naming a namespace nothing here asks for, is caught
    /// (`settings::glass::System::drift`, warned on load and tested). The
    /// greeter is `None` because its material is configured on the
    /// greeter's own compositor (`modules/nixos/desktop/wayland.nix`), not
    /// the session's.
    pub const fn glass(self) -> Option<&'static str> {
        match self {
            Namespace::Bar | Namespace::Osd | Namespace::FaceCue => Some("thin"),
            Namespace::Panel
            | Namespace::Launcher
            | Namespace::Notification
            | Namespace::Pin
            | Namespace::WindowPicker
            | Namespace::Polkit
            | Namespace::Report
            | Namespace::Keybinds => Some("panel"),
            Namespace::SessionLock => Some("lock"),
            Namespace::Jump
            | Namespace::Screenshot
            | Namespace::Greeter
            | Namespace::LockWarm
            | Namespace::MotionProbe
            | Namespace::WallpaperCurtain => None,
        }
    }
}

impl std::fmt::Display for Namespace {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_namespace_is_listed_once_and_spelled_once() {
        let mut names: Vec<&str> = Namespace::ALL.iter().map(|n| n.as_str()).collect();
        names.sort_unstable();
        let before = names.len();
        names.dedup();
        assert_eq!(before, names.len(), "two namespaces share a spelling");
        for n in Namespace::ALL {
            assert_eq!(Namespace::parse(n.as_str()), Some(n));
        }
        assert_eq!(Namespace::parse("swaypplet-switcher"), None);
    }
}
