//! `tokens.css`: every token as a CSS custom property on `:root`.

use std::fmt::Write as _;

use super::{
    BACKDROP_SHADOW_ALPHA, COMPONENT, DURATION, Inputs, Mode, ON_STATUS, RADIUS, Rgb, SPACE,
    SURFACE_KEY, TYPE, categorical, levels, motion, on_backdrop, on_wallpaper, scales, scrim_for,
    status,
};

fn mixed(color: Rgb, share: f64) -> String {
    format!(
        "color-mix(in srgb, {} {}%, transparent)",
        color.css(),
        (share * 100.0).round()
    )
}

/// `tokens.css` for `inputs`: one `:root` block holding the primitives and
/// the semantic tier. The rules in `data/css/` use only the latter.
pub fn css(inputs: Inputs) -> String {
    let s = scales(inputs);
    let st = status(inputs);
    let lv = levels(inputs.mode, inputs.contrast);
    let fg = s.neutral[11];
    let mut out = String::from(
        "/* Generated by src/tokens/ from the theme inputs; see \
         docs/design-system.md. Do not edit. */\n:root {\n",
    );
    let mut put = |name: &str, value: String| {
        let _ = writeln!(out, "  --{name}: {value};");
    };

    // Primitives: private to this block.
    for (i, c) in s.neutral.iter().enumerate() {
        put(&format!("neutral-{}", i + 1), c.css());
    }
    for (i, c) in s.accent.iter().enumerate() {
        put(&format!("accent-{}", i + 1), c.css());
    }

    // Surfaces.
    put("surface-key", mixed(SURFACE_KEY.0, SURFACE_KEY.1));
    put("surface-raised", s.neutral[3].css());
    // The scrim under the lock and the greeter, and the key a card over it
    // paints so the two composite to exactly `surface-key`: at alpha
    // a' = (A − s) / (1 − s) and colour K × A / a', the premultiplied sum is
    // A × K and the alpha A. Dark mode's black 0.20 gives 0.375 and × 4/3;
    // light mode has no scrim (`scrim_for`), and the key is the key.
    let (scrim, scrim_alpha) = scrim_for(inputs.mode);
    put("scrim", mixed(scrim, scrim_alpha));
    let (key, key_alpha) = SURFACE_KEY;
    let under = (key_alpha - scrim_alpha) / (1.0 - scrim_alpha);
    let gain = key_alpha / under;
    put(
        "surface-key-over-scrim",
        format!(
            "color(srgb {:.6} {:.6} {:.6} / {:.6})",
            key.0 * gain,
            key.1 * gain,
            key.2 * gain,
            under
        ),
    );

    // Text.
    put("fg", fg.css());
    put("fg-muted", mixed(fg, lv.muted));
    put("fg-faint", mixed(fg, lv.faint));
    put("fg-disabled", mixed(fg, lv.disabled));

    // Fills on glass, and the state overlays: currentColor at the use site.
    put(
        "fill-1",
        "color-mix(in srgb, currentColor 6%, transparent)".into(),
    );
    put(
        "fill-2",
        "color-mix(in srgb, currentColor 10%, transparent)".into(),
    );
    put(
        "fill-3",
        "color-mix(in srgb, currentColor 16%, transparent)".into(),
    );
    // The fill of a control that cannot be used: the ink at the hairline's
    // share, not currentColor, so the box stays while the label greys.
    put("fill-disabled", mixed(fg, lv.border_subtle));
    put(
        "state-hover",
        "color-mix(in srgb, currentColor 7%, transparent)".into(),
    );
    put(
        "state-pressed",
        "color-mix(in srgb, currentColor 16%, transparent)".into(),
    );
    put(
        "state-selected",
        "color-mix(in srgb, currentColor 10%, transparent)".into(),
    );

    // Lines.
    put("border-subtle", mixed(fg, lv.border_subtle));
    put("border-strong", mixed(fg, lv.border_strong));
    put("focus-ring", mixed(s.accent[10], 0.7));

    // Accent.
    put("accent-bg", s.accent_bg.css());
    put("accent-bg-hover", s.accent[9].css());
    put("on-accent", s.on_accent.css());
    // The second line on an accent fill (a tile's state under its name).
    put("on-accent-muted", mixed(s.on_accent, 0.8));
    put("accent", s.accent[10].css());
    put("accent-tint", mixed(s.accent[8], 0.16));

    // Status.
    put("success", st.success.css());
    put("success-bg", st.success_bg.css());
    put("warning", st.warning.css());
    put("warning-bg", st.warning_bg.css());
    put("danger", st.danger.css());
    put("danger-bg", st.danger_bg.css());
    put("on-status", ON_STATUS.css());
    // Text on bare wallpaper: the ink and its halo follow the wallpaper
    // behind it, not the mode (`backdrop.rs`).
    let ow = on_wallpaper(inputs.backdrop, inputs.mode);
    put("fg-on-wallpaper", ow.ink.css());
    put("halo-on-wallpaper", mixed(ow.halo, ow.halo_alpha));
    // Text on the lock's backdrop: light ink on dark mode's dim, dark ink
    // on light mode's lift, like the backdrop it stands on (`backdrop.rs`).
    let (ink, shadow) = on_backdrop(inputs.mode);
    put("fg-on-backdrop", ink.css());
    put("shadow-on-backdrop", mixed(shadow, BACKDROP_SHADOW_ALPHA));
    put("danger-tint", mixed(st.danger_bg, 0.16));
    put("warning-tint", mixed(st.warning_bg, 0.16));
    put("success-tint", mixed(st.success_bg, 0.16));

    // Categorical: identity only (§3.2).
    for (i, (text, fill)) in categorical(inputs).iter().enumerate() {
        put(&format!("cat-{}", i + 1), text.css());
        put(&format!("cat-{}-bg", i + 1), fill.css());
        put(&format!("cat-{}-tint", i + 1), mixed(*fill, 0.30));
    }

    // Elevation.
    put(
        "shadow-float",
        match inputs.mode {
            Mode::Dark => "none".into(),
            Mode::Light => "0 10px 30px rgb(20 16 10 / 0.16)".into(),
        },
    );
    put("shadow-solid", "0 8px 32px rgb(0 0 0 / 0.45)".into());

    // Type, space, shape, motion.
    for (name, px) in TYPE {
        put(&format!("type-{name}"), format!("{px}px"));
    }
    put("w-light", "300".into());
    put("w-regular", "400".into());
    put("w-strong", "600".into());
    put("w-heavy", "700".into());
    for (i, px) in SPACE.iter().enumerate() {
        put(&format!("space-{}", i + 1), format!("{px}px"));
    }
    for (name, px) in RADIUS {
        put(&format!("radius-{name}"), format!("{px}px"));
    }
    // Motion, scaled by the Motion setting. Zero is one frame's worth, not
    // zero: GTK skips a transition of 0 but the end state must still land.
    let scaled = |ms: f64| (ms * f64::from(inputs.motion) / 100.0).max(1.0).round();
    for (name, ms) in DURATION {
        put(
            &format!("dur-{name}"),
            format!("{}ms", scaled(f64::from(ms))),
        );
    }
    put("ease-standard", motion::STANDARD.css());
    put("ease-decelerate", motion::DECELERATE.css());
    put("ease-accelerate", motion::ACCELERATE.css());
    for m in motion::ALL {
        put(
            &format!("motion-{}", m.name),
            format!("{}ms {}", scaled(m.ms), m.curve.css()),
        );
    }

    // Families (§3.4).
    put(
        "font",
        "\"UbuntuSans Nerd Font\", \"Ubuntu Sans\", \"Noto Sans\", sans-serif".into(),
    );
    put(
        "mono",
        "\"JetBrainsMono Nerd Font\", \"JetBrains Mono\", monospace".into(),
    );

    // Component tokens (§3.9).
    for (name, px) in COMPONENT {
        put(name, format!("{px}px"));
    }
    put(
        "knob",
        match inputs.mode {
            Mode::Dark => fg.css(),
            Mode::Light => Rgb::WHITE.css(),
        },
    );
    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_css_names_every_semantic_token() {
        let css = css(Inputs::default());
        for name in [
            "surface-key",
            "surface-raised",
            "scrim",
            "fg",
            "fg-muted",
            "fg-faint",
            "fg-disabled",
            "fill-1",
            "fill-2",
            "fill-3",
            "fill-disabled",
            "state-hover",
            "state-pressed",
            "state-selected",
            "border-subtle",
            "border-strong",
            "focus-ring",
            "accent-bg",
            "accent-bg-hover",
            "on-accent",
            "accent",
            "accent-tint",
            "success",
            "warning",
            "danger",
            "on-status",
            "fg-on-wallpaper",
            "halo-on-wallpaper",
            "fg-on-backdrop",
            "shadow-on-backdrop",
            "type-body",
            "space-5",
            "radius-card",
            "dur-fast",
            "ease-standard",
            "motion-state",
            "motion-enter",
            "motion-exit",
            "motion-travel",
        ] {
            assert!(css.contains(&format!("  --{name}: ")), "missing --{name}");
        }
    }
}
